name: Deploy

on: [push]

jobs:
  deploy:

    if: contains(github.event.head_commit.message, 'deploy')
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }} 
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts
      - name: Deploy with rsync
        run: rsync -avz . ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/root/stacks/seguridadUnileonNuevo/html